### PR TITLE
fix: fixes linter errors and black configuration

### PR DESCRIPTION
**Pull request by martinm82**

### CODE REVIEW

**Comment by eugene-davis** [comment]
Regarding the build failures, one easy and reasonable fix would be to remove the Python 3.5 support in the next version. We should probably drop it from being supported by default in the pipeline as well, given that it EOL this month. See https://www.python.org/dev/peps/pep-0478/

**Comment by eugene-davis** [comment]
As for the other build failure, do you know what is going on with the docs build?

**Comment by martinm82** [comment]
> Regarding the build failures, one easy and reasonable fix would be to remove the Python 3.5 support in the next version. We should probably drop it from being supported by default in the pipeline as well, given that it EOL this month. See https://www.python.org/dev/peps/pep-0478/

**Comment by martinm82** [comment]
> As for the other build failure, do you know what is going on with the docs build?

No idea yet. But I wanted to check in detail what is going on with the builds and fix them.

**Comment by martinm82** [comment]
Closing this PR since #356 has fixed already these issues

**Pull request closed without merging**
